### PR TITLE
Update PARTY_PARROTS list

### PR DESCRIPTION
**Pull request by globalundo**
Slack nowadays has a wild arrange of party parrots. I propose to use all of them by default!

### CODE REVIEW

**Comment by Shrugs** [comment]
Great idea! Can we use the names standardized by http://cultofthepartyparrot.com/ ?

**Comment by globalundo** [comment]
> Can we use the names standardized by http://cultofthepartyparrot.com/ ?
Unfortunately, no: slack uses it's own shortcuts for emoji. It is possible to create a custom mapping between these two, but I would rather see it as a separate patchset/pull request

**Comment by Shrugs** [comment]
Oh, are these emojis in slack by default now?

**Comment by globalundo** [comment]
>Oh, are these emojis in slack by default now?

Exactly. These are all the party-parrots available is slack
2016-09-30-171021_617x40_scrot

**Comment by Shrugs** [comment]
Interesting! I don't see all of these available in my slack channel; do you have to create a new slack channel for these to be added?

**Pull request closed without merging**
